version: "3.8"
networks:
  mariadb:
services:
  mariadb:
    container_name: mariadb
    image: mariadb:lts-jammy
    ports:
      - ${MARIADB_EXTERNAL_PORT}:${MARIADB_INTERNAL_PORT}
    volumes:
      - ./volumes/conf.d:/etc/mysql/conf.d
      - ./volumes/db/data:/var/lib/mysql
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always